### ISSUE TITLE
how can user specify baundrate?

### ISSUE THREAD

**Issue by lizheng851123** [snarlistic/jpnevulator#2]
seems no option to specify a baundrate

**Comment by snarlistic** [comment]
Hi lizheng851123,

On Tue, Jun 28, 2016 at 11:47:38PM -0700, lizheng851123 wrote:

> Subject: [snarlistic/jpnevulator] how can user specify baundrate? (#2)
> [cut]
> seems no option to specify a baundrate

True. Please see stty(1).

## 

$ cat ~/.signature
Freddy Spierenburg freddy@snarl.nl         http://freddy.snarl.nl/
GnuPG fingerprint: C71E F201 840C 8998 4D3F F675 B507 BF7D 9218 273E
$ # Please read http://www.ietf.org/rfc/rfc2015.txt before complain!
