### ISSUE TITLE
In --read mode it takes out incoming data

### ISSUE THREAD

**Issue by adipascu** [snarlistic/jpnevulator#5]
It looks like about half of the incoming data goes into the sniffer, and the other half goes into my app.
This is causing incoming packet loss, I can not successfully use the app I am working to debug, and the sniffer shows incomplete information.

I am running it with `jpnevulator --ascii --timing-print --tty /dev/ttyACM0 --read`. 
Am I missing something? Is this working as intended?

**Comment by snarlistic** [comment]
Could it be perhaps that both your application and jpnevulator open /dev/ttyACM0 at the same time? You can't do that and it causes undefined behaviour like which you describe in your message.

Please see the [FAQ](https://github.com/snarlistic/jpnevulator/blob/master/FAQ) and manual page. Read upon the --pty and --pass options. This should solve your problems.

**Comment by adipascu** [comment]
Thank you very much, that was exactly what I needed!
